using System.Collections.Generic;
using System.Linq;
using Rapidity.Http.DynamicProxies;
using Sample.Service;
using Xunit;

namespace Rapidity.Http.Tests
{
    /// <summary>
    /// 
    /// </summary>
    public class ProxyGeneratorTest
    {
        [Fact]
        public void GeneratorTest()
        {
            var type = ProxyGenerator.Generate(typeof(ITokenService));
        }

        [Fact]
        public void BuildTemplateTest()
        {
            var type = typeof(ITokenService);
            var template = ProxyGenerator.BuildTemplate(type);
        }

        [Fact]
        public void TestService_Template_Build_Test()
        {
            var type = typeof(ITestService);
            var template = ProxyGenerator.BuildTemplate(type);

            Assert.NotNull(template);
            Assert.Equal(1, template.ClassList.Count);
            var className = template.ClassList.First().Name;
            Assert.Equal("AutoGeneratedTestService", className);
        }

        [Fact]
        public void TypeTemplateTest()
        {
            var type = typeof(IDictionary<string, IList<int>>);
            var template = new TypeTemplate(type);
            var str = template.ToString();
        }
    }
}