using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Rapidity.Http.DynamicProxies;
using Sample.Service;
using Xunit;

namespace Rapidity.Http.Tests
{
    /// <summary>
    /// 
    /// </summary>
    public class ProxyGeneratorTest
    {
        [Fact]
        public void GeneratorTest()
        {
            var types = new Type[] { typeof(ITokenService) };
            var type = ProxyGenerator.Generate(types);
        }

        [Fact]
        public void BuildTemplateTest()
        {
            var types = new Type[] { typeof(ITokenService) };
            var template = ProxyGenerator.BuildTemplate(types);
            var code = ProxyGenerator.GenerateCode(template);
        }

        [Fact]
        public void TestService_Template_Build_Test()
        {
            var types = new Type[] { typeof(ITestService) };
            var template = ProxyGenerator.BuildTemplate(types);

            Assert.NotNull(template);
            Assert.Equal(1, template.ClassList.Count);
            var className = template.ClassList.First().Name;
            Assert.Equal("AutoGeneratedTestService", className);

            var assembly = ProxyGenerator.Generate(types);
        }

        [Fact]
        public void GenericService_Template_Build_Test()
        {
            var types = new Type[] { typeof(IGenericService<,>), typeof(ITestService), typeof(ITokenService), typeof(IUserService) };
            var template = ProxyGenerator.BuildTemplate(types);

            Assert.NotNull(template);
            Assert.Equal(types.Length, template.ClassList.Count);
            var className = template.ClassList.First().Name;
            //Assert.Equal("AutoGeneratedGenericService`1", className);

            var code = ProxyGenerator.GenerateCode(template);

            var assembly = ProxyGenerator.Generate(types);
        }

        [Fact]
        public void TypeTemplateTest()
        {
            var type = typeof(IDictionary<string, IList<int>>);
            var template = new TypeTemplate(type);
            var str = template.ToString();
        }

    }
}